---
title: "Mini_project_3"
author: "Emily M., Sylvie L., and Hannah R.D."
date: "April 3, 2018"
output: 
  html_document:
    code_folding: hide
---

```{r warning= FALSE, message= FALSE}
library(tidyverse)
library(leaflet)
library(sf)
library(macleish)
library(ggplot2)
```

```{r warning= FALSE, message= FALSE}
#Attaining the orchard live weather data from Professor Baumer's R package (this part is not our code)
macleish <- etl("macleish")
macleish %>%
  etl_update()
whately <- macleish %>%
  tbl("whately")
whately %>%
  mutate(the_year = strftime('%Y', when)) %>%
  group_by(the_year) %>%
  summarize(N = n(), begin = min(when), end = max(when), avg_temp = mean(temperature))
orchard <- macleish %>%
  tbl("orchard")
orchard %>%
  mutate(the_year = strftime('%Y', when)) %>%
  group_by(the_year) %>%
  summarize(N = n(), begin = min(when), end = max(when), avg_temp = mean(temperature))

#Collecting the wild not-data sets that orchard and whately are, getting the sap data and the forest data (this part is our code)
orchard_data <-collect(orchard)
whately_data <- collect(whately)
sap <- macleish::maple_sap
forests <- macleish_layers[["forests"]]
```

```{r warning= FALSE, message= FALSE}
#What types of maple forests are there? Where are they?

forests <- forests%>%
  rename("forest_type"="Sheet1__Na")%>%
  mutate(area= st_area(forests))

forest_areas <- forests %>%
  group_by(forest_type)%>%
  summarise(total_area= sum(area))%>%
  filter(str_detect(forest_type, "Maple"))

#Making a palette for the two types of Maple forests
fm_pal <- colorFactor(
  palette= c('#42f47a', '#137a33'),
  domain= forest_areas$forest_type
)

#Leaflet plot to map where the maple forests are

leaflet()%>%
  addTiles()%>%
  addPolygons(data=forest_areas, color= ~fm_pal(forest_type))%>%
  addMarkers(lng= -72.68055556, lat = 42.44888889, label= "Whately Monitoring Station")
  
```

```{r warning= FALSE, message= FALSE}
#Wrangling the orchard and whately data

orchard_data$Date <- format(as.POSIXct(orchard_data$when, format= "%Y-%m-%dT%H:%M:%SZ"), "%Y-%m-%d")
orchard_data$Year <- format(as.POSIXct(orchard_data$when, format= "%Y-%m-%dT%H:%M:%SZ"), "%Y")
orchard_data$Month <- format(as.POSIXct(orchard_data$when, format="%Y-%m-%dT%H:%M:%SZ"), "%m")
orchard_data$Day <- format(as.POSIXct(orchard_data$when, format="%Y-%m-%dT%H:%M:%SZ"), "%d")
orchard_data$Time <- format(as.POSIXct(orchard_data$when, format="%Y-%m-%dT%H:%M:%SZ"), "%H.%M%S")

whately_data$Date <- format(as.POSIXct(whately_data$when, format= "%Y-%m-%dT%H:%M:%SZ"), "%Y-%m-%d")
whately_data$Year <- format(as.POSIXct(whately_data$when,format=("%Y-%m-%dT%H:%M:%SZ")),"%Y")
whately_data$Month <- format(as.POSIXct(whately_data$when,format=("%Y-%m-%dT%H:%M:%SZ")),"%m")
whately_data$Day <- format(as.POSIXct(whately_data$when,format=("%Y-%m-%dT%H:%M:%SZ")),"%d")
whately_data$Time <- format(as.POSIXct(whately_data$when, format="%Y-%m-%dT%H:%M:%SZ"), "%H.%M%S")
```

```{r warning= FALSE, message= FALSE}
#more wrangling

Night_weather <- function(name_arg){
  na.omit(name_arg)%>%
  transform(temperature= as.numeric(temperature),
            wind_speed= as.numeric(wind_speed),
            wind_dir = as.numeric(wind_dir),
            rel_humidity= as.numeric(rel_humidity),
            pressure= as.numeric(pressure))%>%
  filter(Time< 6|Time > 18)%>%
  select(temperature:Day)%>%
  group_by(Year, Month, Day)%>%
  summarise(min_night_temp = min(temperature),
            night_wind_speed = mean(wind_speed),
            night_wind_dir = mean(wind_dir),
            night_rel_humidity = mean(rel_humidity),
            night_pressure = mean(pressure))%>%
    filter(min_night_temp < 0)
}

Day_weather <- function(name_arg){
  na.omit(name_arg)%>%
  transform(temperature= as.numeric(temperature),
            wind_speed= as.numeric(wind_speed),
            wind_dir = as.numeric(wind_dir),
            rel_humidity= as.numeric(rel_humidity),
            pressure= as.numeric(pressure))%>%
  filter(Time>6|Time<18)%>%
  select(temperature:Day)%>%
  group_by(Year, Month, Day)%>%
  summarise(max_day_temp = max(temperature),
            day_wind_speed = mean(wind_speed),
            day_wind_dir = mean(wind_dir),
            day_rel_humidity = mean(rel_humidity),
            day_pressure = mean(pressure))%>%
    filter(max_day_temp > 0)
}

ideal_days <- function(name_arg) {
  Day_weather(name_arg)%>%
    inner_join(Night_weather(name_arg), by = c("Year", "Month", "Day"))
}

```

```{r warning= FALSE, message= FALSE}
#using those functions

Whately_Weather <- ideal_days(whately_data)

#the orchard weather is really only for ground temperatures and in the middle of a field, whearas the whately station is in the forest and gets readings from the air so it's more useful. 
Orchard_Weather <- ideal_days(orchard_data)

```

```{r warning= FALSE, message= FALSE}
#wrangling the sap data a bit

sap$Year <- format(as.POSIXct(sap$when, format= "%Y-%m-%d"), "%Y")
sap$Month <- format(as.POSIXct(sap$when, format="%Y-%m-%d"), "%m")
sap$Day <- format(as.POSIXct(sap$when, format="%Y-%m-%d"), "%d")

Sap <- sap %>%
  rename("Sap_in_gal"="sap")%>%
  select(Sap_in_gal, Year:Day)

WW_and_Sap <- Whately_Weather %>%
  left_join(Sap, by = c("Year", "Month", "Day"))

WW_and_Sap$Date <- as.Date(with(WW_and_Sap, paste(Year, Month, Day, sep= "-")), "%Y-%m-%d")

#editing data so we can see trends
WW_and_Sap_Summary <- WW_and_Sap %>%
  group_by(Year, Month)%>%
  summarise(total_days= n())

Months_of_Sap <- WW_and_Sap_Summary%>%
  mutate(Month = recode(Month, "01"="January", "02"="February", "03"="March", "04"="April", "10"="October", "11"="November", "12"="December"))

Spring_sap <- Months_of_Sap %>%
  filter(Month== "January"|Month=="February"|Month=="March"|Month=="April")
  
```

```{r warning=FALSE, message= FALSE}
#plotting to see some trends
ggplot(WW_and_Sap_Summary, aes(x= Year, y=total_days ))+
  geom_point()+
  facet_wrap(~Month)

ggplot(WW_and_Sap_Summary, aes(x= Month, y= total_days))+
  geom_point()+
  facet_wrap(~Year)

ggplot(Spring_sap, aes(x=Month, y= total_days, color= Year))+
  geom_point()+
  geom_line(aes(group=Year))+
  scale_x_discrete(limits=c("January","February","March","April"))


months <- function(name_arg){
  Spring_sap%>%
    filter(Month== name_arg)%>%
    ggplot(aes(x=Year, y= total_days))+
  geom_point()
}
  
months("January")
```

```{r warning= FALSE, message= FALSE}
#OK so i want to map the days in a month that are reasonable out of the total days in that month versus time so I'm rewriting these functions so I can do that

Night_weather_all <- function(name_arg){
  na.omit(name_arg)%>%
  transform(temperature= as.numeric(temperature),
            wind_speed= as.numeric(wind_speed),
            wind_dir = as.numeric(wind_dir),
            rel_humidity= as.numeric(rel_humidity),
            pressure= as.numeric(pressure))%>%
  filter(Time< 6|Time > 18, Month== "01"|Month== "02"|Month=="03"|Month=="04")%>%
  select(temperature:Day)%>%
  group_by(Year, Month, Day)%>%
  summarise(min_night_temp = min(temperature),
            night_wind_speed = mean(wind_speed),
            night_wind_dir = mean(wind_dir),
            night_rel_humidity = mean(rel_humidity),
            night_pressure = mean(pressure))%>%
    filter(Month < 5)%>%
    mutate(correct_night_temp= ifelse(min_night_temp <0, 1, 0))
}

Day_weather_all <- function(name_arg){
  na.omit(name_arg)%>%
  transform(temperature= as.numeric(temperature),
            wind_speed= as.numeric(wind_speed),
            wind_dir = as.numeric(wind_dir),
            rel_humidity= as.numeric(rel_humidity),
            pressure= as.numeric(pressure))%>%
  filter(Time>6|Time<18, Month== "01"|Month== "02"|Month=="03"|Month=="04")%>%
  select(temperature:Day)%>%
  group_by(Year, Month, Day)%>%
  summarise(max_day_temp = max(temperature),
            day_wind_speed = mean(wind_speed),
            day_wind_dir = mean(wind_dir),
            day_rel_humidity = mean(rel_humidity),
            day_pressure = mean(pressure))%>%
    mutate(correct_day_temp= ifelse(max_day_temp>0, 1, 0))
}

all_days <- function(name_arg) {
  Day_weather_all(name_arg)%>%
    inner_join(Night_weather_all(name_arg), by = c("Year", "Month", "Day"))%>%
    mutate(temp_total = correct_night_temp+ correct_day_temp,
           correct_temp = ifelse(temp_total == 2, "TRUE", "FALSE")) %>%
    select(Year:correct_temp, -correct_night_temp, -correct_day_temp, -temp_total)%>%
    mutate(DATE = as.Date(paste(Year, Month, Day, sep= '-'), "%Y-%m-%d"))
    
}

```

```{r warning= FALSE, message= FALSE}
weather_and_all_possible_days <- all_days(whately_data)
```

```{r warning= FALSE, message= FALSE}
